Implemented interrupt queuing system
emanuelen5/kitchen-timer pull request #6
Opened 2024-04-23 06:12 UTC by nperozzi

I implemented the queuing system in the rotary-encoder library.
1) queuing interrupts: The ISRs debounce and add interrupts to the interruptQueue[]
2) dequeuing interrupts: The dequeuing_interrupts is called in the main loop. It checks if there are interrupts queued triggers the first one and moves the front of the queue variable. Then it processes the interrupt depending on which one it is.

2024-04-23 08:28 UTC, emanuelen5 requested changes
Nice job :)

By moving the queue implementation to its own file, we can make it self-contained (event possible to reuse for other project) and testable. So I think that is top-priority. To do that, we need to make the following changes:

1. Move the `first`/`rear` pointers into the the queue struct (or class) so that it's self-contained.
2. Move the implementation of the queue to another file, so it's independent of the rotary encoder, and state machine implementations.
3. In the `cw_rotation_cb` function in the state machine, call `queue_interrupt(CW_ROTATION)`, and vice versa in `ccw_rotation_cb`. Then in the main `loop` function, dequeue the events and call the `step_state` function.

2024-04-23 08:28 UTC, emanuelen5 commented on src/rotary-encoder.cpp
> +    if (front != rear) {
If you invert the logic of the check, you can exit early and reduce the indentation of the function, which makes it easier to read (indentation in general increases the perceived complexity):

```c
    if (front == rear) {
        return;
    }
```

If you, at the same time make it a named function, then you can also remove the comment, which makes the code's intent easier to read.

```suggestion
    if (event_queue_is_empty(&queue)) {
        return;
    }
```

2024-04-23 17:39 UTC, nperozzi commented on src/rotary-encoder.cpp
> +int rear = 0;
This I understand. Makes so much more sense when you make the array of type event_t.

2024-04-23 17:45 UTC, nperozzi commented on src/rotary-encoder.cpp
> +    if (front != rear) {
As you can imagine, I did a lot of this with ChatGPT 😏.
When working with the front and rear variables I noticed that both increase and none of them decrease. I wonder if they would overflow at some point.?

2024-04-27 06:46 UTC, nperozzi commented
I made the modification that we agreed on Thursday 😊:
- I made a separate function to test if the queue is full
- I broke out the event_queue library from the rotary-encoder library.
I see that my new commits have been pushed correctly into the interrupt_queue branch and they seem to have been added to this same pull request (great! 😃). 
Looking forward to hearing the feedback 😄

2024-04-27 12:19 UTC, emanuelen5 requested changes
I have some suggestions that I think will improve the reuse-ability, test-ability and readability:

1. Don't use global state
2. Make the event_queue into a regular queue that takes any uint8_t values (not just the events from the state-machine)
3. Return value instead of using a function callback

2024-04-27 12:19 UTC, emanuelen5 commented on src/event_queue.cpp
> +        handlingEvent(eventQueue.data[eventQueue.front]);
I don't think it adds any value to have a callback function since it is a side effect (which are harder to debug and use). Instead, I would make the function return the value directly

```c
typedef struct {
    uint8_t value;
    bool is_valid;
} value_t;

value_t dequeue(queue_t *queue) {
    value_t v = {0};

    if (queue_is_empty(queue)) {
        v.is_valid = false;
        return v;
    }

    v.value = queue->data[queue->front];
    v.is_valid = true;

    queue->front = (queue->front + 1) % QUEUE_SIZE;
    return v;
}
```

2024-04-28 05:08 UTC, nperozzi commented on src/event_queue.h
> +} event_t;
I agree, I wanted to keep the event definition in the main. I tried to pass `even_t` as an `int` but couldn´t make it work. With `uint8_t` it works.
> and convert it to/from the event_t type at the same time as you're reading/writing to the queue.
I am guessing that you are talking about "type-casting". For reading it did not seem that I needed it and I am not doing any writing. Let me know if I am missing something. :)

2024-04-28 05:12 UTC, nperozzi commented on src/rotary-encoder.cpp
I am not sure I understand what you mean 🤔. Should I do `git commit` per individual files instead of doing it every time I fix/implement something?

2024-04-28 05:15 UTC, nperozzi commented on src/rotary-encoder.h
If we revert it, the `init_rotary_encoder` call will not match the rotary-encoder lib implementation of that function. 
Why do we need to revert this file? 🤔

2024-04-28 05:27 UTC, nperozzi commented on src/event_queue.cpp
> +}
Ups. I did not think about that 😅. I fixed it now.

2024-04-28 05:39 UTC, nperozzi commented on src/event_queue.cpp
> +void queuing_event(event_t event)
I like standards :)

2024-04-28 20:40 UTC, emanuelen5 commented on src/rotary-encoder.h
I performed a merge and reverted the changes I was referring to. :) I don't think this PR will need to change anything in the rotary-encoder files.

2024-04-28 20:41 UTC, emanuelen5 commented on src/rotary-encoder.cpp
Fixed in 1d131e8a0627228e9718ad851e2eacfd6b597c19 :)

2024-04-28 20:44 UTC, emanuelen5 commented on src/event_queue.h
> +} event_t;
> I am guessing that you are talking about "type-casting"

Exactly. But it seems like we have permissive compiler settings. Usually things like passing an `event_t` type to a function that takes `uint8_t` isn't allowed unless you explicitly type cast it to that type. Like here:

https://github.com/emanuelen5/kitchen-timer/blob/1d131e8a0627228e9718ad851e2eacfd6b597c19/src/envs/state_machine/main.cpp#L53

2024-04-29 04:02 UTC, nperozzi commented on src/rotary-encoder.cpp
I am still not sure what you are referring to with "We should be able to revert all changes made to this file." 😅. In that commit, it seems like you moved the rotary-encoder library to the lib folder.

2024-04-29 04:45 UTC, nperozzi commented on src/event_queue.cpp
> +static eventHandlerFunction handlingEvent;
This is now done in a982ae8 but I am not 100% sure I have done it right.

2024-04-29 18:09 UTC, emanuelen5 commented on src/rotary-encoder.cpp
The rotary-encoder files were already moved in be0ebdf93b03014af53cee275c921d2f01c037d5, which were merged into the `main` branch. So I just reverted the file content to what was on the `main` branch: https://github.com/emanuelen5/kitchen-timer/tree/main/lib/rotary-encoder/src

I used the command 
```bash
git checkout main -- lib/rotary-encoder/src
```

2024-04-29 19:04 UTC, nperozzi commented on src/event_queue.cpp
> +        handlingEvent(eventQueue.data[eventQueue.front]);
I implemented this in 001b96d.
I do not love how the implementation looks in the loop 😄
`    value_t dequeue_value = dequeue_event(&eventQueue);
    if (dequeue_value.is_valid)
    {
        step_state(dequeue_value.value);
    }
`

2024-04-29 19:07 UTC, nperozzi commented
I think I fixed all the comments 👏

2024-04-30 19:59 UTC, emanuelen5 reviewed
I think it looks really good now. We can just decide on if we want to rename the type and value, and then do a squash before merge.

2024-04-30 19:59 UTC, emanuelen5 commented on src/event_queue.cpp
> +        handlingEvent(eventQueue.data[eventQueue.front]);
I see your point. We should choose a better name for the type `value_t`. Perhaps something like `queue_ret_t` is better. And the value should suffice to be called `event`, since it's an event that we're trying to pull off from the queue. Then I think it'd read better:

```c
queue_ret_t event = dequeue_event(&queue);
if (event.is_valid) {
    step_state(event.value);
}
```

What do you think?

2024-04-30 20:01 UTC, emanuelen5 commented
By the way: I pushed some changes above to minimize the diff and just format the files with clang-formatter. In f97932c57bb9442d8df3ebc4e195b703fe0add7a I changed so we in fact use the `event_t` type when we should.

2024-05-02 04:08 UTC, nperozzi commented
- I can see how now the event_queue could work independently from the rest of the code.
- Yes, we can do a squash (if I googled correctly, it is the rearrangement of the git history so it is more readable)
- Some variables and functions could change name, yes. For example, the library is called "even_queue" but, I guess that the queue could eventually be of things other than events too.
- We can bring these things up during today's meetup. 😊

Looking forward to merging this branch!

2024-05-02 17:24 UTC, merged